# -*-sh-*-
# this file cleans all temporary run files and also the symbolic links
# from the data directory

# clean dueca stuff
clean-dueca-rundir

# clean symbolic links
find . -type l -exec rm {} \;

# run script, if desired
RUNSCRIPT=1
if [ $RUNSCRIPT = "1" ]; then
    rm -f runscript
fi

# clean the user's stuff (that's you, you have to add your commands here!)
rm -rf datalog-*.hdf5 initials-world-*.toml recordings-world-*.ddff \
    __pycache__ runlogs dueca_run.x